[package]
name = "df"
version = "0.0.1"
authors = []

[lib]
name = "uu_df"
path = "df.rs"

[dependencies]
getopts = "0.2.14"
clap = "2.24.1"
libc = "0.2.26"
uucore = { path="../uucore" }

[[bin]]
name = "df"
path = "main.rs"
